language: php

php:
  - 5.5
  - 5.6
  - hhvm

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-dist

before_script:
  - ./vendor/bin/parallel-lint -e php,phpt src tests

script:
  - ./vendor/bin/tester -p php ./tests
